# Generated by Django 4.1.5 on 2023-01-26 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_demand'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'qweqw', 'verbose_name_plural': 'Задgsgfdfgdfgdачи'},
        ),
        migrations.RemoveField(
            model_name='demand',
            name='demand',
        ),
        migrations.RemoveField(
            model_name='demand',
            name='title',
        ),
        migrations.AddField(
            model_name='demand',
            name='amountOfVacancies',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='demand',
            name='managerAmountOfVacancies',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='demand',
            name='managerSalaryPerYear',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='demand',
            name='salaryPerYear',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='task',
            name='task',
            field=models.TextField(verbose_name='sdfgdfg'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=50, verbose_name='fsgsdfgsdfgdx'),
        ),
    ]
