# Generated by Django 4.1.5 on 2023-01-26 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_task_options_remove_demand_demand_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.AlterModelOptions(
            name='demand',
            options={},
        ),
        migrations.AddField(
            model_name='demand',
            name='year',
            field=models.IntegerField(default=2008),
        ),
    ]
